### ISSUE TITLE
Not Being able to convert some scratch projects

### ISSUE THREAD

**Issue by thebrowngaming** [edxtech/scratchexporter#4]
Hi, So I get the links from scratch projects and paste them into the url bar like i'm suppose to but it keeps saying that the link dose'nt work. Can You fix this? If you fix this then that would be awesome :D - The Brown Gaming

**Comment by ed6767** [comment]
Try getting rid of the "/" at the end.
I'll rewrite this once Scratch 3.0 goes into Beta.

**Comment by thebrowngaming** [comment]
Okay Thank you so much, I'll have to try and see if this works

**Comment by ed6767** [comment]
Let me know if you have any more issues.

**Comment by thebrowngaming** [comment]
So I found another issue. So when I convert projects with the links without slashes their a problem. Some of the sprites are in half. Also if you could make it where the application saves it self than it would help out a lot. Also when we get the exe can you make it where  we can still be able to use the exe without the phosphorus
